
auth.token=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

defaults.org=inordersview
defaults.project=laso-coach-mobile

defaults.url=https://sentry.io/
