/**
 * Liste complète des pays du monde en français
 * Tous les pays sont en ordre alphabétique, avec la République démocratique du Congo en premier
 */

export interface Country {
  name: string;
  code: string; // Code ISO 3166-1 alpha-2
  phonePrefix: string; // Indicatif téléphonique
}

// ✅ République démocratique du Congo en premier
const RDC: Country = {
  name: 'République démocratique du Congo',
  code: 'CD',
  phonePrefix: '+243',
};

// Liste complète des pays du monde en français, triés alphabétiquement
const ALL_COUNTRIES: Country[] = [
  RDC, // ✅ Toujours en premier
  { name: 'Afghanistan', code: 'AF', phonePrefix: '+93' },
  { name: 'Afrique du Sud', code: 'ZA', phonePrefix: '+27' },
  { name: 'Albanie', code: 'AL', phonePrefix: '+355' },
  { name: 'Algérie', code: 'DZ', phonePrefix: '+213' },
  { name: 'Allemagne', code: 'DE', phonePrefix: '+49' },
  { name: 'Andorre', code: 'AD', phonePrefix: '+376' },
  { name: 'Angola', code: 'AO', phonePrefix: '+244' },
  { name: 'Antigua-et-Barbuda', code: 'AG', phonePrefix: '+1' },
  { name: 'Arabie saoudite', code: 'SA', phonePrefix: '+966' },
  { name: 'Argentine', code: 'AR', phonePrefix: '+54' },
  { name: 'Arménie', code: 'AM', phonePrefix: '+374' },
  { name: 'Australie', code: 'AU', phonePrefix: '+61' },
  { name: 'Autriche', code: 'AT', phonePrefix: '+43' },
  { name: 'Azerbaïdjan', code: 'AZ', phonePrefix: '+994' },
  { name: 'Bahamas', code: 'BS', phonePrefix: '+1' },
  { name: 'Bahreïn', code: 'BH', phonePrefix: '+973' },
  { name: 'Bangladesh', code: 'BD', phonePrefix: '+880' },
  { name: 'Barbade', code: 'BB', phonePrefix: '+1' },
  { name: 'Belgique', code: 'BE', phonePrefix: '+32' },
  { name: 'Belize', code: 'BZ', phonePrefix: '+501' },
  { name: 'Bénin', code: 'BJ', phonePrefix: '+229' },
  { name: 'Bhoutan', code: 'BT', phonePrefix: '+975' },
  { name: 'Biélorussie', code: 'BY', phonePrefix: '+375' },
  { name: 'Birmanie', code: 'MM', phonePrefix: '+95' },
  { name: 'Bolivie', code: 'BO', phonePrefix: '+591' },
  { name: 'Bosnie-Herzégovine', code: 'BA', phonePrefix: '+387' },
  { name: 'Botswana', code: 'BW', phonePrefix: '+267' },
  { name: 'Brésil', code: 'BR', phonePrefix: '+55' },
  { name: 'Brunei', code: 'BN', phonePrefix: '+673' },
  { name: 'Bulgarie', code: 'BG', phonePrefix: '+359' },
  { name: 'Burkina Faso', code: 'BF', phonePrefix: '+226' },
  { name: 'Burundi', code: 'BI', phonePrefix: '+257' },
  { name: 'Cambodge', code: 'KH', phonePrefix: '+855' },
  { name: 'Cameroun', code: 'CM', phonePrefix: '+237' },
  { name: 'Canada', code: 'CA', phonePrefix: '+1' },
  { name: 'Cap-Vert', code: 'CV', phonePrefix: '+238' },
  { name: 'Chili', code: 'CL', phonePrefix: '+56' },
  { name: 'Chine', code: 'CN', phonePrefix: '+86' },
  { name: 'Chypre', code: 'CY', phonePrefix: '+357' },
  { name: 'Colombie', code: 'CO', phonePrefix: '+57' },
  { name: 'Comores', code: 'KM', phonePrefix: '+269' },
  { name: 'Congo', code: 'CG', phonePrefix: '+242' },
  { name: 'Corée du Nord', code: 'KP', phonePrefix: '+850' },
  { name: 'Corée du Sud', code: 'KR', phonePrefix: '+82' },
  { name: 'Costa Rica', code: 'CR', phonePrefix: '+506' },
  { name: 'Côte d\'Ivoire', code: 'CI', phonePrefix: '+225' },
  { name: 'Croatie', code: 'HR', phonePrefix: '+385' },
  { name: 'Cuba', code: 'CU', phonePrefix: '+53' },
  { name: 'Danemark', code: 'DK', phonePrefix: '+45' },
  { name: 'Djibouti', code: 'DJ', phonePrefix: '+253' },
  { name: 'Dominique', code: 'DM', phonePrefix: '+1' },
  { name: 'Égypte', code: 'EG', phonePrefix: '+20' },
  { name: 'Émirats arabes unis', code: 'AE', phonePrefix: '+971' },
  { name: 'Équateur', code: 'EC', phonePrefix: '+593' },
  { name: 'Érythrée', code: 'ER', phonePrefix: '+291' },
  { name: 'Espagne', code: 'ES', phonePrefix: '+34' },
  { name: 'Estonie', code: 'EE', phonePrefix: '+372' },
  { name: 'Eswatini', code: 'SZ', phonePrefix: '+268' },
  { name: 'États-Unis', code: 'US', phonePrefix: '+1' },
  { name: 'Éthiopie', code: 'ET', phonePrefix: '+251' },
  { name: 'Fidji', code: 'FJ', phonePrefix: '+679' },
  { name: 'Finlande', code: 'FI', phonePrefix: '+358' },
  { name: 'France', code: 'FR', phonePrefix: '+33' },
  { name: 'Gabon', code: 'GA', phonePrefix: '+241' },
  { name: 'Gambie', code: 'GM', phonePrefix: '+220' },
  { name: 'Géorgie', code: 'GE', phonePrefix: '+995' },
  { name: 'Ghana', code: 'GH', phonePrefix: '+233' },
  { name: 'Grèce', code: 'GR', phonePrefix: '+30' },
  { name: 'Grenade', code: 'GD', phonePrefix: '+1' },
  { name: 'Guatemala', code: 'GT', phonePrefix: '+502' },
  { name: 'Guinée', code: 'GN', phonePrefix: '+224' },
  { name: 'Guinée-Bissau', code: 'GW', phonePrefix: '+245' },
  { name: 'Guinée équatoriale', code: 'GQ', phonePrefix: '+240' },
  { name: 'Guyana', code: 'GY', phonePrefix: '+592' },
  { name: 'Haïti', code: 'HT', phonePrefix: '+509' },
  { name: 'Honduras', code: 'HN', phonePrefix: '+504' },
  { name: 'Hongrie', code: 'HU', phonePrefix: '+36' },
  { name: 'Inde', code: 'IN', phonePrefix: '+91' },
  { name: 'Indonésie', code: 'ID', phonePrefix: '+62' },
  { name: 'Irak', code: 'IQ', phonePrefix: '+964' },
  { name: 'Iran', code: 'IR', phonePrefix: '+98' },
  { name: 'Irlande', code: 'IE', phonePrefix: '+353' },
  { name: 'Islande', code: 'IS', phonePrefix: '+354' },
  { name: 'Israël', code: 'IL', phonePrefix: '+972' },
  { name: 'Italie', code: 'IT', phonePrefix: '+39' },
  { name: 'Jamaïque', code: 'JM', phonePrefix: '+1' },
  { name: 'Japon', code: 'JP', phonePrefix: '+81' },
  { name: 'Jordanie', code: 'JO', phonePrefix: '+962' },
  { name: 'Kazakhstan', code: 'KZ', phonePrefix: '+7' },
  { name: 'Kenya', code: 'KE', phonePrefix: '+254' },
  { name: 'Kirghizistan', code: 'KG', phonePrefix: '+996' },
  { name: 'Kiribati', code: 'KI', phonePrefix: '+686' },
  { name: 'Koweït', code: 'KW', phonePrefix: '+965' },
  { name: 'Laos', code: 'LA', phonePrefix: '+856' },
  { name: 'Lesotho', code: 'LS', phonePrefix: '+266' },
  { name: 'Lettonie', code: 'LV', phonePrefix: '+371' },
  { name: 'Liban', code: 'LB', phonePrefix: '+961' },
  { name: 'Liberia', code: 'LR', phonePrefix: '+231' },
  { name: 'Libye', code: 'LY', phonePrefix: '+218' },
  { name: 'Liechtenstein', code: 'LI', phonePrefix: '+423' },
  { name: 'Lituanie', code: 'LT', phonePrefix: '+370' },
  { name: 'Luxembourg', code: 'LU', phonePrefix: '+352' },
  { name: 'Macédoine du Nord', code: 'MK', phonePrefix: '+389' },
  { name: 'Madagascar', code: 'MG', phonePrefix: '+261' },
  { name: 'Malaisie', code: 'MY', phonePrefix: '+60' },
  { name: 'Malawi', code: 'MW', phonePrefix: '+265' },
  { name: 'Maldives', code: 'MV', phonePrefix: '+960' },
  { name: 'Mali', code: 'ML', phonePrefix: '+223' },
  { name: 'Malte', code: 'MT', phonePrefix: '+356' },
  { name: 'Maroc', code: 'MA', phonePrefix: '+212' },
  { name: 'Îles Marshall', code: 'MH', phonePrefix: '+692' },
  { name: 'Maurice', code: 'MU', phonePrefix: '+230' },
  { name: 'Mauritanie', code: 'MR', phonePrefix: '+222' },
  { name: 'Mexique', code: 'MX', phonePrefix: '+52' },
  { name: 'Micronésie', code: 'FM', phonePrefix: '+691' },
  { name: 'Moldavie', code: 'MD', phonePrefix: '+373' },
  { name: 'Monaco', code: 'MC', phonePrefix: '+377' },
  { name: 'Mongolie', code: 'MN', phonePrefix: '+976' },
  { name: 'Monténégro', code: 'ME', phonePrefix: '+382' },
  { name: 'Mozambique', code: 'MZ', phonePrefix: '+258' },
  { name: 'Namibie', code: 'NA', phonePrefix: '+264' },
  { name: 'Nauru', code: 'NR', phonePrefix: '+674' },
  { name: 'Népal', code: 'NP', phonePrefix: '+977' },
  { name: 'Nicaragua', code: 'NI', phonePrefix: '+505' },
  { name: 'Niger', code: 'NE', phonePrefix: '+227' },
  { name: 'Nigéria', code: 'NG', phonePrefix: '+234' },
  { name: 'Norvège', code: 'NO', phonePrefix: '+47' },
  { name: 'Nouvelle-Zélande', code: 'NZ', phonePrefix: '+64' },
  { name: 'Oman', code: 'OM', phonePrefix: '+968' },
  { name: 'Ouganda', code: 'UG', phonePrefix: '+256' },
  { name: 'Ouzbékistan', code: 'UZ', phonePrefix: '+998' },
  { name: 'Pakistan', code: 'PK', phonePrefix: '+92' },
  { name: 'Palaos', code: 'PW', phonePrefix: '+680' },
  { name: 'Palestine', code: 'PS', phonePrefix: '+970' },
  { name: 'Panama', code: 'PA', phonePrefix: '+507' },
  { name: 'Papouasie-Nouvelle-Guinée', code: 'PG', phonePrefix: '+675' },
  { name: 'Paraguay', code: 'PY', phonePrefix: '+595' },
  { name: 'Pays-Bas', code: 'NL', phonePrefix: '+31' },
  { name: 'Pérou', code: 'PE', phonePrefix: '+51' },
  { name: 'Philippines', code: 'PH', phonePrefix: '+63' },
  { name: 'Pologne', code: 'PL', phonePrefix: '+48' },
  { name: 'Portugal', code: 'PT', phonePrefix: '+351' },
  { name: 'Qatar', code: 'QA', phonePrefix: '+974' },
  { name: 'Roumanie', code: 'RO', phonePrefix: '+40' },
  { name: 'Royaume-Uni', code: 'GB', phonePrefix: '+44' },
  { name: 'Russie', code: 'RU', phonePrefix: '+7' },
  { name: 'Rwanda', code: 'RW', phonePrefix: '+250' },
  { name: 'Saint-Kitts-et-Nevis', code: 'KN', phonePrefix: '+1' },
  { name: 'Saint-Marin', code: 'SM', phonePrefix: '+378' },
  { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC', phonePrefix: '+1' },
  { name: 'Sainte-Lucie', code: 'LC', phonePrefix: '+1' },
  { name: 'Salomon', code: 'SB', phonePrefix: '+677' },
  { name: 'Salvador', code: 'SV', phonePrefix: '+503' },
  { name: 'Samoa', code: 'WS', phonePrefix: '+685' },
  { name: 'São Tomé-et-Príncipe', code: 'ST', phonePrefix: '+239' },
  { name: 'Sénégal', code: 'SN', phonePrefix: '+221' },
  { name: 'Serbie', code: 'RS', phonePrefix: '+381' },
  { name: 'Seychelles', code: 'SC', phonePrefix: '+248' },
  { name: 'Sierra Leone', code: 'SL', phonePrefix: '+232' },
  { name: 'Singapour', code: 'SG', phonePrefix: '+65' },
  { name: 'Slovaquie', code: 'SK', phonePrefix: '+421' },
  { name: 'Slovénie', code: 'SI', phonePrefix: '+386' },
  { name: 'Somalie', code: 'SO', phonePrefix: '+252' },
  { name: 'Soudan', code: 'SD', phonePrefix: '+249' },
  { name: 'Soudan du Sud', code: 'SS', phonePrefix: '+211' },
  { name: 'Sri Lanka', code: 'LK', phonePrefix: '+94' },
  { name: 'Suède', code: 'SE', phonePrefix: '+46' },
  { name: 'Suisse', code: 'CH', phonePrefix: '+41' },
  { name: 'Suriname', code: 'SR', phonePrefix: '+597' },
  { name: 'Syrie', code: 'SY', phonePrefix: '+963' },
  { name: 'Tadjikistan', code: 'TJ', phonePrefix: '+992' },
  { name: 'Tanzanie', code: 'TZ', phonePrefix: '+255' },
  { name: 'Tchad', code: 'TD', phonePrefix: '+235' },
  { name: 'Tchéquie', code: 'CZ', phonePrefix: '+420' },
  { name: 'Thaïlande', code: 'TH', phonePrefix: '+66' },
  { name: 'Timor oriental', code: 'TL', phonePrefix: '+670' },
  { name: 'Togo', code: 'TG', phonePrefix: '+228' },
  { name: 'Tonga', code: 'TO', phonePrefix: '+676' },
  { name: 'Trinité-et-Tobago', code: 'TT', phonePrefix: '+1' },
  { name: 'Tunisie', code: 'TN', phonePrefix: '+216' },
  { name: 'Turkménistan', code: 'TM', phonePrefix: '+993' },
  { name: 'Turquie', code: 'TR', phonePrefix: '+90' },
  { name: 'Tuvalu', code: 'TV', phonePrefix: '+688' },
  { name: 'Ukraine', code: 'UA', phonePrefix: '+380' },
  { name: 'Uruguay', code: 'UY', phonePrefix: '+598' },
  { name: 'Vanuatu', code: 'VU', phonePrefix: '+678' },
  { name: 'Vatican', code: 'VA', phonePrefix: '+39' },
  { name: 'Venezuela', code: 'VE', phonePrefix: '+58' },
  { name: 'Viêt Nam', code: 'VN', phonePrefix: '+84' },
  { name: 'Yémen', code: 'YE', phonePrefix: '+967' },
  { name: 'Zambie', code: 'ZM', phonePrefix: '+260' },
  { name: 'Zimbabwe', code: 'ZW', phonePrefix: '+263' },
  { name: 'Autre', code: 'XX', phonePrefix: '+' },
];

// ✅ Exporter uniquement les noms des pays (pour compatibilité avec le code existant)
export const COUNTRIES = ALL_COUNTRIES.map(country => country.name);

// ✅ Exporter le mapping des indicatifs téléphoniques
export const COUNTRY_PHONE_PREFIXES: Record<string, string> = ALL_COUNTRIES.reduce((acc, country) => {
  acc[country.name] = country.phonePrefix;
  return acc;
}, {} as Record<string, string>);

// ✅ Fonction pour obtenir l'indicatif d'un pays
export const getPhonePrefix = (countryName: string): string => {
  return COUNTRY_PHONE_PREFIXES[countryName] || '+';
};

// ✅ Exporter la liste complète avec toutes les informations
export const COUNTRIES_DATA = ALL_COUNTRIES;

